"""Consultation PDF export — a shareable clinical report via reportlab."""

from __future__ import annotations

from io import BytesIO
from typing import Any, Dict
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

PRIMARY = colors.HexColor("#3683F8")
INK = colors.HexColor("#060606")
MUTED = colors.HexColor("#6B7280")


def _para(text: str, style) -> Paragraph:
    return Paragraph(escape(text).replace("\n", "<br/>"), style)


def render_consultation_pdf(consultation: Any, explanation: Dict[str, Any]) -> bytes:
    """Render a Consultation ORM row (+ derived explanation) to PDF bytes."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title="SEPHIROTH Consultation Report",
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], textColor=INK, fontSize=16)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=PRIMARY, fontSize=11.5)
    body = ParagraphStyle("body", parent=styles["BodyText"], textColor=INK, fontSize=9.5, leading=13)
    small = ParagraphStyle("small", parent=body, textColor=MUTED, fontSize=8)

    story = [Paragraph("SEPHIROTH — Consultation Report", h1)]

    user_name = getattr(getattr(consultation, "user", None), "name", "") or "—"
    meta = Table(
        [
            ["Clinician", user_name, "Patient", consultation.patient_id or "—"],
            [
                "Date",
                consultation.created_at.strftime("%Y-%m-%d %H:%M UTC"),
                "Consultation ID",
                consultation.id[:8],
            ],
        ],
        colWidths=[28 * mm, 60 * mm, 32 * mm, 54 * mm],
    )
    meta.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
                ("TEXTCOLOR", (2, 0), (2, -1), MUTED),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LINEBELOW", (0, -1), (-1, -1), 0.5, colors.HexColor("#D8D8D8")),
            ]
        )
    )
    story += [meta, Spacer(1, 6 * mm)]

    story += [Paragraph("Clinical question", h2), _para(consultation.query, body), Spacer(1, 3 * mm)]
    story += [Paragraph("AI response", h2), _para(consultation.answer, body), Spacer(1, 3 * mm)]

    if consultation.agents:
        story += [
            Paragraph("Agents involved", h2),
            _para(", ".join(consultation.agents), body),
            Spacer(1, 3 * mm),
        ]

    report = consultation.citation_report or {}
    story += [
        Paragraph("Citation Guard", h2),
        _para(
            f"{len(report.get('verified', []))} citation(s) verified against tool output; "
            f"{len(report.get('fabricated', []))} fabricated citation(s) removed.",
            body,
        ),
    ]
    for citation in report.get("verified", []):
        story.append(_para(f"✓ {citation}", small))
    for citation in report.get("fabricated", []):
        story.append(_para(f"✗ removed: {citation}", small))
    story.append(Spacer(1, 3 * mm))

    steps = (explanation or {}).get("steps", [])
    if steps:
        story.append(Paragraph("Reasoning trace", h2))
        for step in steps:
            story.append(_para(f"[{step.get('agent', '?')}] {step.get('action', '')}", small))
        story.append(Spacer(1, 5 * mm))

    story.append(
        _para(
            "Decision support only — not a diagnosis. Generated by a locally-hosted AI "
            "system; all content requires review by a qualified healthcare professional.",
            small,
        )
    )

    doc.build(story)
    return buffer.getvalue()


def render_result_share_pdf(share: Any, patient_name: str) -> bytes:
    """Render a `ResultShare` (a lab/imaging result a clinician shared with
    a patient) to PDF bytes, for the patient portal's download button.
    Patient-facing, so — unlike `render_consultation_pdf` above, which is a
    clinician tool — this one is written in Spanish, matching the portal
    UI it's downloaded from."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title="Resultado médico — SEPHIROTH",
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], textColor=INK, fontSize=16)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=PRIMARY, fontSize=11.5)
    body = ParagraphStyle("body", parent=styles["BodyText"], textColor=INK, fontSize=9.5, leading=13)
    small = ParagraphStyle("small", parent=body, textColor=MUTED, fontSize=8)

    event = share.event
    story = [Paragraph("SEPHIROTH — Resultado médico", h1)]

    type_label = "Imagen" if event.type == "imaging" else "Laboratorio"
    meta = Table(
        [
            ["Paciente", patient_name or "—", "Tipo", type_label],
            [
                "Fecha del resultado",
                event.date.isoformat(),
                "Compartido el",
                share.shared_at.strftime("%Y-%m-%d"),
            ],
        ],
        colWidths=[35 * mm, 55 * mm, 30 * mm, 54 * mm],
    )
    meta.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
                ("TEXTCOLOR", (2, 0), (2, -1), MUTED),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LINEBELOW", (0, -1), (-1, -1), 0.5, colors.HexColor("#D8D8D8")),
            ]
        )
    )
    story += [meta, Spacer(1, 6 * mm)]

    story += [Paragraph(event.title, h2)]

    if share.message:
        story += [
            Paragraph("Mensaje de tu médico", h2),
            _para(share.message, body),
            Spacer(1, 3 * mm),
        ]

    story += [Paragraph("Detalle", h2), _para(event.detail, body), Spacer(1, 3 * mm)]

    if event.ai_generated:
        story.append(
            _para(
                "Este resumen fue redactado por un agente de IA y revisado por tu médico "
                "antes de compartirlo contigo.",
                small,
            )
        )
        story.append(Spacer(1, 3 * mm))

    story.append(
        _para(
            "Apoyo a la decisión clínica únicamente — no es un diagnóstico. Consulta siempre "
            "a tu médico antes de actuar sobre esta información.",
            small,
        )
    )

    doc.build(story)
    return buffer.getvalue()
