"""Drift guard: fails if a SQLAlchemy model changed without a matching
Alembic migration being written. This is the actual safety net Alembic
was introduced for — everything else (baseline migration, Supabase
stamp) is one-time setup; this test is what keeps it honest going
forward.

Skips automatically when no local Postgres is reachable (e.g. plain CI,
which has no Postgres service) — the same "skip if infra unavailable"
pattern already used by tests/test_embeddings_matching.py. Never touches
data: `alembic check` only introspects the live schema and compares it
against `Base.metadata`; it runs no DDL.
"""

import socket

import pytest

LOCAL_POSTGRES_HOST = "localhost"
LOCAL_POSTGRES_PORT = 5433
# Deliberately independent of settings.database_url, which may point at
# Supabase in a developer's .env — this check always targets the local
# docker-compose Postgres (same credentials as docker-compose.yml/
# .env.example), regardless of what the app itself is currently configured
# to talk to.
LOCAL_POSTGRES_URL = (
    f"postgresql+asyncpg://clinical_ai:clinical_ai_password@"
    f"{LOCAL_POSTGRES_HOST}:{LOCAL_POSTGRES_PORT}/clinical_ai_db"
)


def _local_postgres_reachable() -> bool:
    try:
        with socket.create_connection((LOCAL_POSTGRES_HOST, LOCAL_POSTGRES_PORT), timeout=1):
            return True
    except OSError:
        return False


pytestmark = pytest.mark.skipif(
    not _local_postgres_reachable(),
    reason=(
        f"no Postgres reachable at {LOCAL_POSTGRES_HOST}:{LOCAL_POSTGRES_PORT} — "
        "run `docker compose up -d postgres`"
    ),
)


def test_no_pending_schema_changes():
    """Fails if any SQLAlchemy model in data/schemas differs from what
    migrations/versions/ would produce — i.e. someone changed a model and
    forgot to write `alembic revision --autogenerate`."""
    from io import StringIO

    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected

    cfg = Config(stdout=StringIO())
    cfg.set_main_option("script_location", "migrations")
    cfg.set_main_option("sqlalchemy.url", LOCAL_POSTGRES_URL)

    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "A model in data/schemas differs from the current Alembic head — "
            f'run `alembic revision --autogenerate -m "..."` to add the missing migration.\n{exc}'
        )
