"""Event subscribers that turn something clinical into an inbox task.

Kept separate from the workflow definitions next to it because it is not a
workflow: no steps, no schedule, no retries. It subscribes to the same events
the escalation and reminder definitions subscribe to and records the work in
`tasks` so a clinician can see it.

Why a subscriber rather than a call inside `sephiroth.safety.alerts`: that
module already emits `CLINICAL_ALERT` inside the transaction that creates the
alert, so subscribing costs one line in `subscriptions.py` and changes nothing
at the emitting call site. The tradeoff is latency — the outbox dispatches on
the tick, so a task appears within a tick of its alert rather than instantly.
That is the right trade for alerts, which are generated by a background sweep
anyway. It is the wrong trade for a clinician's own action, which is why
resolving an alert closes its task synchronously instead (`routers/alerts.py`).
"""

from __future__ import annotations

from sqlalchemy.ext.asyncio import AsyncSession

from data.schemas import Alert
from sephiroth.workflows.events import WorkflowEvent

from ..services import task_service

#: Alerts are already categorised; the task keeps that category so the inbox
#: can filter by it without a second vocabulary to keep in step.
_ALERT_CATEGORY = "alert"


async def on_clinical_alert(session: AsyncSession, event: WorkflowEvent) -> None:
    alert = await session.get(Alert, event.entity_id)
    if alert is None or alert.status != "active":
        # Resolved between emit and dispatch. Creating the task now would put
        # finished work in front of someone.
        return

    await task_service.create_task(
        session,
        source_type="alert",
        source_id=alert.id,
        category=_ALERT_CATEGORY,
        severity=alert.severity,
        title=alert.title,
        detail=alert.detail or "",
        patient_id=alert.patient_id,
        # Keyed on the alert row, so re-dispatching the same event — or a
        # second event for an alert that already has a task — is a no-op.
        dedupe_key=f"alert:{alert.id}",
        context={
            "alert_category": alert.category,
            "alert_kind": alert.kind,
            "source": alert.source,
        },
        now=alert.created_at,
    )


__all__ = ["on_clinical_alert"]
