"""encounters and encounter orders (SPEC-023)

Revision ID: 0d3e6f312a90
Revises: d7b3e91c045a
Create Date: 2026-09-06

Purely additive: two new tables, and one CHECK constraint replaced.

Autogenerated against a fresh local Postgres, then hand-corrected in three
places autogenerate cannot get right:

- `core.crypto` is imported. Autogenerate writes the custom type's fully
  qualified name into the column definitions but never adds the import, so the
  generated file does not run. Same fixup as the baseline revision.
- The redundant second index on `encounter_orders.encounter_id` is dropped.
  `index=True` on the column already makes one; two indexes on one column cost
  every write and buy nothing.
- `ck_task_source_type` is replaced to admit `encounter`. Alembic does not
  diff CHECK constraints, so a source type added to the model without this
  would pass every test on SQLite (which does not enforce it in
  `create_all`-built schemas the same way) and fail on the first real signing
  in production.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import core.crypto

# revision identifiers, used by Alembic.
revision: str = "0d3e6f312a90"
down_revision: Union[str, Sequence[str], None] = "d7b3e91c045a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "encounters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("clinician_id", sa.String(length=36), nullable=False),
        sa.Column("appointment_id", sa.String(length=36), nullable=True),
        sa.Column("specialty", sa.String(length=40), server_default="general", nullable=False),
        sa.Column("status", sa.String(length=12), server_default="draft", nullable=False),
        sa.Column("chief_complaint", core.crypto.EncryptedText(), nullable=False),
        sa.Column("vitals", core.crypto.EncryptedJSON(), nullable=False),
        sa.Column("subjective", core.crypto.EncryptedText(), nullable=False),
        sa.Column("objective", core.crypto.EncryptedText(), nullable=False),
        sa.Column("assessment", core.crypto.EncryptedText(), nullable=False),
        sa.Column("plan", core.crypto.EncryptedText(), nullable=False),
        sa.Column("patient_instructions", core.crypto.EncryptedText(), nullable=False),
        sa.Column("note_source", sa.String(length=10), server_default="clinician", nullable=False),
        sa.Column("note_model", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("signed_at", sa.DateTime(), nullable=True),
        sa.Column("signed_by", sa.String(length=36), nullable=True),
        sa.Column("amended_at", sa.DateTime(), nullable=True),
        sa.Column("amendment_reason", sa.String(length=300), server_default="", nullable=False),
        sa.Column("clinical_note_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "amended_at IS NULL OR amendment_reason <> ''", name="ck_encounter_amendment_reason"
        ),
        sa.CheckConstraint("note_source IN ('clinician','llm','template')", name="ck_encounter_note_source"),
        sa.CheckConstraint(
            "status = 'draft' OR (signed_at IS NOT NULL AND signed_by IS NOT NULL)",
            name="ck_encounter_signed_requires_signer",
        ),
        sa.CheckConstraint("status IN ('draft','signed','amended')", name="ck_encounter_status"),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clinical_note_id"],
            ["clinical_notes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encounters_clinician_id"), "encounters", ["clinician_id"], unique=False)
    op.create_index("ix_encounters_clinician_status", "encounters", ["clinician_id", "status"], unique=False)
    op.create_index(op.f("ix_encounters_patient_id"), "encounters", ["patient_id"], unique=False)
    op.create_index("ix_encounters_patient_started", "encounters", ["patient_id", "started_at"], unique=False)
    op.create_index(op.f("ix_encounters_status"), "encounters", ["status"], unique=False)
    op.create_index("ix_encounters_status_started", "encounters", ["status", "started_at"], unique=False)
    op.create_index(
        "uq_encounter_appointment",
        "encounters",
        ["appointment_id"],
        unique=True,
        sqlite_where=sa.text("appointment_id IS NOT NULL"),
        postgresql_where=sa.text("appointment_id IS NOT NULL"),
    )
    op.create_table(
        "encounter_orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("detail", core.crypto.EncryptedText(), nullable=False),
        sa.Column("due_in_days", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('lab','imaging','referral','followup','medication')", name="ck_encounter_order_kind"
        ),
        sa.CheckConstraint("due_in_days IS NULL OR due_in_days > 0", name="ck_encounter_order_due"),
        sa.ForeignKeyConstraint(["encounter_id"], ["encounters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_encounter_orders_encounter_id"), "encounter_orders", ["encounter_id"], unique=False
    )

    # Signing files one task per order, so the task table has to admit the new
    # source. Not detected by autogenerate -- CHECK constraints are not diffed.
    op.drop_constraint("ck_task_source_type", "tasks", type_="check")
    op.create_check_constraint(
        "ck_task_source_type",
        "tasks",
        "source_type IN ('alert','approval','followup','result','appointment',"
        "'automation','consultation','deteriorating','interaction','encounter')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_task_source_type", "tasks", type_="check")
    op.create_check_constraint(
        "ck_task_source_type",
        "tasks",
        "source_type IN ('alert','approval','followup','result','appointment',"
        "'automation','consultation','deteriorating','interaction')",
    )

    op.drop_index(op.f("ix_encounter_orders_encounter_id"), table_name="encounter_orders")
    op.drop_table("encounter_orders")
    op.drop_index(
        "uq_encounter_appointment",
        table_name="encounters",
        sqlite_where=sa.text("appointment_id IS NOT NULL"),
        postgresql_where=sa.text("appointment_id IS NOT NULL"),
    )
    op.drop_index("ix_encounters_status_started", table_name="encounters")
    op.drop_index(op.f("ix_encounters_status"), table_name="encounters")
    op.drop_index("ix_encounters_patient_started", table_name="encounters")
    op.drop_index(op.f("ix_encounters_patient_id"), table_name="encounters")
    op.drop_index("ix_encounters_clinician_status", table_name="encounters")
    op.drop_index(op.f("ix_encounters_clinician_id"), table_name="encounters")
    op.drop_table("encounters")
