"""recurring appointment series, waitlist, notifications

Revision ID: 115cdf0b0ed4
Revises: 32a957e66854
Create Date: 2026-08-17 14:52:04.887036

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "115cdf0b0ed4"
down_revision: Union[str, Sequence[str], None] = "32a957e66854"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment_series",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("clinician_id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("frequency", sa.String(length=10), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="active", nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("occurrence_count > 0", name="ck_appointment_series_count_positive"),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appointment_series_clinician_id"), "appointment_series", ["clinician_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointment_series_patient_id"), "appointment_series", ["patient_id"], unique=False
    )
    op.create_table(
        "appointment_waitlist",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("clinician_id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("window_start", sa.DateTime(), nullable=False),
        sa.Column("window_end", sa.DateTime(), nullable=False),
        sa.Column("notified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("window_start < window_end", name="ck_waitlist_window_order"),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appointment_waitlist_clinician_id"), "appointment_waitlist", ["clinician_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointment_waitlist_created_at"), "appointment_waitlist", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_appointment_waitlist_patient_id"), "appointment_waitlist", ["patient_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("message", sa.String(length=300), nullable=False),
        sa.Column("related_appointment_id", sa.String(length=36), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["related_appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.add_column("appointments", sa.Column("series_id", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_appointments_series_id"), "appointments", ["series_id"], unique=False)
    op.create_foreign_key(None, "appointments", "appointment_series", ["series_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "appointments", type_="foreignkey")
    op.drop_index(op.f("ix_appointments_series_id"), table_name="appointments")
    op.drop_column("appointments", "series_id")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_appointment_waitlist_patient_id"), table_name="appointment_waitlist")
    op.drop_index(op.f("ix_appointment_waitlist_created_at"), table_name="appointment_waitlist")
    op.drop_index(op.f("ix_appointment_waitlist_clinician_id"), table_name="appointment_waitlist")
    op.drop_table("appointment_waitlist")
    op.drop_index(op.f("ix_appointment_series_patient_id"), table_name="appointment_series")
    op.drop_index(op.f("ix_appointment_series_clinician_id"), table_name="appointment_series")
    op.drop_table("appointment_series")
    # ### end Alembic commands ###
