"""add trace and telemetry scalar columns

Revision ID: 233988357f83
Revises: eef6397408fa
Create Date: 2026-08-16 21:25:31.106364

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "233988357f83"
down_revision: Union[str, Sequence[str], None] = "eef6397408fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("consultations", sa.Column("trace", sa.JSON(), nullable=True))
    op.add_column("consultations", sa.Column("trace_id", sa.String(length=64), nullable=True))
    op.add_column("consultations", sa.Column("risk_level", sa.String(length=20), nullable=True))
    op.add_column("consultations", sa.Column("abstained", sa.Boolean(), nullable=True))
    op.add_column("consultations", sa.Column("supported_claim_ratio", sa.Float(), nullable=True))
    op.create_index(op.f("ix_consultations_abstained"), "consultations", ["abstained"], unique=False)
    op.create_index(op.f("ix_consultations_risk_level"), "consultations", ["risk_level"], unique=False)
    op.create_index(
        op.f("ix_consultations_supported_claim_ratio"),
        "consultations",
        ["supported_claim_ratio"],
        unique=False,
    )
    op.create_index(op.f("ix_consultations_trace_id"), "consultations", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_consultations_trace_id"), table_name="consultations")
    op.drop_index(op.f("ix_consultations_supported_claim_ratio"), table_name="consultations")
    op.drop_index(op.f("ix_consultations_risk_level"), table_name="consultations")
    op.drop_index(op.f("ix_consultations_abstained"), table_name="consultations")
    op.drop_column("consultations", "supported_claim_ratio")
    op.drop_column("consultations", "abstained")
    op.drop_column("consultations", "risk_level")
    op.drop_column("consultations", "trace_id")
    op.drop_column("consultations", "trace")
    # ### end Alembic commands ###
