"""double booking exclusion constraint

Revision ID: 32a957e66854
Revises: 08a4a2ef03ab
Create Date: 2026-08-17 14:43:13.686304

Hand-written, not autogenerated: SQLAlchemy has no `EXCLUDE USING gist`
construct, so this is raw `op.execute`, dialect-guarded exactly like the
`CREATE EXTENSION IF NOT EXISTS vector` guard in
`dff332c99951_initial_schema.py` — a no-op on the SQLite test fixture,
which never sees this file at all (`Base.metadata.create_all` doesn't run
migrations).

`appointments.start_at`/`end_at` are `DateTime()` (timestamp WITHOUT time
zone, always stored as UTC-naive by convention — see every handler in
`platform/api/routers/scheduling.py`), so the range type here is
`tsrange`, not `tstzrange` — using `tstzrange` against a tz-naive column
would implicitly involve the session timezone on cast, which is exactly
the kind of silent, environment-dependent bug this constraint exists to
rule out.

This is a last-resort integrity backstop, not the primary conflict
mechanism: `book_appointment`/`update_appointment` still do their own
SELECT-then-check first (UX-facing, exercised by the whole SQLite test
suite); this constraint only fires on the genuinely-simultaneous race
those two sequential, unlocked queries can miss, and the routers now
catch `IntegrityError` and turn it into the same 409 either way.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32a957e66854"
down_revision: Union[str, Sequence[str], None] = "08a4a2ef03ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE appointments ADD CONSTRAINT ck_appointments_no_overlap
        EXCLUDE USING gist (
            clinician_id WITH =,
            tsrange(start_at, end_at, '[)') WITH &&
        ) WHERE (status = 'booked')
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute("ALTER TABLE appointments DROP CONSTRAINT ck_appointments_no_overlap")
