"""patient portal roles and invites

Revision ID: 3b2f5725233c
Revises: 233988357f83
Create Date: 2026-08-17 11:56:13.005580

Hand-fix: autogenerate named `users.patient_id`'s foreign key `None` in
both `upgrade()`/`downgrade()` (no `naming_convention` is configured on
`Base.metadata`) — `op.drop_constraint(None, ...)` is not droppable by
name, so `downgrade()` would fail. Named it explicitly
(`fk_users_patient_id_patients`) in both directions.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b2f5725233c"
down_revision: Union[str, Sequence[str], None] = "233988357f83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient_invites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("issued_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(), nullable=True),
        sa.Column("redeemed_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["redeemed_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patient_invites_patient_id"), "patient_invites", ["patient_id"], unique=False)
    op.add_column(
        "users", sa.Column("role", sa.String(length=20), server_default="clinician", nullable=False)
    )
    op.add_column("users", sa.Column("patient_id", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_users_patient_id"), "users", ["patient_id"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_foreign_key("fk_users_patient_id_patients", "users", "patients", ["patient_id"], ["id"])
    op.create_check_constraint(
        "ck_users_patient_has_record", "users", "role != 'patient' OR patient_id IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_users_patient_has_record", "users", type_="check")
    op.drop_constraint("fk_users_patient_id_patients", "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_patient_id"), table_name="users")
    op.drop_column("users", "patient_id")
    op.drop_column("users", "role")
    op.drop_index(op.f("ix_patient_invites_patient_id"), table_name="patient_invites")
    op.drop_table("patient_invites")
    # ### end Alembic commands ###
