"""consultation outcome tracking

Revision ID: 91538cb9b156
Revises: 1e8ae674a4e5
Create Date: 2026-08-18 10:52:31.700575

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91538cb9b156"
down_revision: Union[str, Sequence[str], None] = "1e8ae674a4e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("consultations", sa.Column("acted_on", sa.Boolean(), nullable=True))
    op.add_column("consultations", sa.Column("acted_at", sa.DateTime(), nullable=True))
    op.add_column("consultations", sa.Column("outcome", sa.String(length=20), nullable=True))
    op.add_column("consultations", sa.Column("outcome_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_consultations_acted_on"), "consultations", ["acted_on"], unique=False)
    op.create_index(op.f("ix_consultations_outcome"), "consultations", ["outcome"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_consultations_outcome"), table_name="consultations")
    op.drop_index(op.f("ix_consultations_acted_on"), table_name="consultations")
    op.drop_column("consultations", "outcome_at")
    op.drop_column("consultations", "outcome")
    op.drop_column("consultations", "acted_at")
    op.drop_column("consultations", "acted_on")
    # ### end Alembic commands ###
