"""add missing index on pending_actions.workflow_step_id

Revision ID: b1028e8958d0
Revises: a7c9e1f3b5d2
Create Date: 2026-08-21 22:31:17.440548

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1028e8958d0"
down_revision: Union[str, Sequence[str], None] = "a7c9e1f3b5d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_pending_actions_workflow_step_id"), "pending_actions", ["workflow_step_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pending_actions_workflow_step_id"), table_name="pending_actions")
    # ### end Alembic commands ###
