"""workflow deferrals + non-empty drafts + no-show index (SPEC-020)

Revision ID: c4f1a86d2e70
Revises: 98e0a1e35b4a
Create Date: 2026-09-06

Three changes, one of which is not purely additive and needs care:

1. `workflow_steps.deferred_count` -- new counter, defaults to 0.
2. `appointments(status, end_at)` -- the index the no-show sweep selects on.
   Neither existing index leads with `status`.
3. `ck_pending_action_draft_nonempty` -- **this one can fail on live data.**
   Every `PendingAction` created by `followup_check_due` before this phase was
   written with `draft_text=''` (that was the defect), so any still-pending row
   would violate the constraint the moment it is added. The backfill below
   fills them first, and it is deliberately a plain SQL UPDATE rather than a
   call into `sephiroth.workflows.templates`: a migration must not import
   application code, whose behaviour can change underneath a historical
   revision.

Written by hand rather than autogenerated -- the local Postgres was not
running -- so the `pending_actions` backfill and the two DDL statements were
derived from the model diff directly. `tests/test_alembic_migration.py` is the
drift guard that catches a mistake here, and it self-skips without a database.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4f1a86d2e70"
down_revision: Union[str, Sequence[str], None] = "98e0a1e35b4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: What a pre-SPEC-020 empty draft becomes. Intentionally generic and
#: intentionally frozen: it is a historical value, not a template that should
#: track whatever `render_followup_draft` says today.
BACKFILL_TEXT = (
    "Hola,\n\n"
    "Te escribimos desde la consulta para saber cómo has seguido.\n\n"
    "Si algo ha empeorado o tienes una duda, respóndenos por este medio."
)


def upgrade() -> None:
    op.add_column(
        "workflow_steps",
        sa.Column("deferred_count", sa.Integer(), server_default="0", nullable=False),
    )

    op.create_index("ix_appointments_status_end", "appointments", ["status", "end_at"])

    # Fill before constraining, or the constraint fails on the rows the defect
    # created. Scoped to rows that are actually empty so nothing already
    # reviewed is rewritten.
    op.execute(
        sa.text("UPDATE pending_actions SET draft_text = :text WHERE draft_text = ''").bindparams(
            text=BACKFILL_TEXT
        )
    )
    op.create_check_constraint("ck_pending_action_draft_nonempty", "pending_actions", "draft_text <> ''")


def downgrade() -> None:
    op.drop_constraint("ck_pending_action_draft_nonempty", "pending_actions", type_="check")
    op.drop_index("ix_appointments_status_end", table_name="appointments")
    op.drop_column("workflow_steps", "deferred_count")
