"""add verification_report and abstention columns

Revision ID: eef6397408fa
Revises: dff332c99951
Create Date: 2026-08-16 18:52:28.644888

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eef6397408fa"
down_revision: Union[str, Sequence[str], None] = "dff332c99951"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate produced NOT NULL columns with no default, which would
    # fail against any pre-existing consultations row (e.g. Supabase's live
    # data). server_default='{}' matches the model's Python-side
    # `default=dict` for existing rows too.
    op.add_column(
        "consultations",
        sa.Column("verification_report", sa.JSON(), nullable=False, server_default="{}"),
    )
    op.add_column(
        "consultations",
        sa.Column("abstention", sa.JSON(), nullable=False, server_default="{}"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consultations", "abstention")
    op.drop_column("consultations", "verification_report")
    # ### end Alembic commands ###
